/**
    Save/Restore floating-point control words, so that
    rounding-mode doesn't change wildly in a shared library.

    Copied from Dplug 16.5.5, dplug/core/fpcontrol.d, unchanged apart from
    the module name, so that the core does not depend on Dplug. The plugin
    still uses Dplug itself.

    Copyright: Guillaume Piolat 2015-2016.
    License:   Boost Software License 1.0, reproduced below.

    Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/
module stimulation.fpcontrol;

version(X86)
    version = isX86;
version(X86_64)
    version = isX86;

import inteli.xmmintrin;

nothrow @nogc:

/**
    This struct ensures that floating point is save/restored
    and set consistently in plugin callbacks.
*/
struct FPControl
{
nothrow @nogc:
    void initialize()
    {
        // Save and set control word. This works because
        // intel-intrinsics emulate that control word for
        // ARM.
        {
            // Get current SSE control word
            storedMXCSR = _mm_getcsr();

            // Set current SSE control word:
            // - Flush denormals to zero
            // - Denormals Are Zeros
            // - all exception masked
            _mm_setcsr(0x9fff);
        }

        // There is a x86 specific path-here because x86 has
        // a FPU control word in addition to the SSE control
        // word.
        version(isX86)
        {
            // store FPU control word
            fpuState = getFPUControlState();

            // masks all floating-point exceptions,
            // sets rounding to nearest,
            // and sets the x87 FPU precision to 64 bits
            ushort control = 0x037f;

            // Very rarely useful debug options below:

            // 1. Looking for problems? Unmask all errors.
            //control = 0x0340;

            // 2. Looking for denormals only? This unmasks
            // denormal creation and denormal use
            // exceptions.
            //control = 0x036d;

            setFPUControlState(control);
        }
    }

    ~this()
    {
        _mm_setcsr(storedMXCSR);

        version(isX86)
        {
            // restore FPU control word
            setFPUControlState(fpuState);
        }
    }

    version(isX86)
    {
        ushort fpuState;
    }
    uint storedMXCSR;
}


version(isX86)
{
    version(D_InlineAsm_X86)
        version = InlineX86Asm;
    else version(D_InlineAsm_X86_64)
        version = InlineX86Asm;

    ushort getFPUControlState()
    {
        version (InlineX86Asm)
        {
            short cont;
            asm nothrow @nogc
            {
                xor EAX, EAX;
                fstcw cont;
            }
            return cont;
        }
        else
            static assert(0);
    }

    void setFPUControlState(ushort newState)
    {
        version (InlineX86Asm)
        {
            asm nothrow @nogc
            {
                fclex;
                fldcw newState;
            }
        }
        else
            static assert(0);
    }
}

