/**
    Slices allocated with malloc, for the core's @nogc buffers.

    Copied from Dplug 16.5.5, dplug/core/nogc.d (mallocSlice,
    mallocSliceNoInit, freeSlice), so that the core does not depend on
    Dplug. The plugin still uses Dplug itself.

    Changed from the original: mallocSliceNoInit fails with an
    OutOfMemoryError when the size overflows or malloc returns null, where
    the original returned a slice over a null pointer. Each changed line
    is marked "Changed from Dplug".

    Copyright: Copyright 2016-2024, Guillaume Piolat.
    License:   Boost Software License 1.0, reproduced below.

    Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/
module stimulation.nogc;

import core.stdc.string : memcpy;
import core.stdc.stdlib : malloc, free;
import core.exception : onOutOfMemoryError; // Changed from Dplug: added

/// Allocates a slice with `malloc`.
T[] mallocSlice(T)(size_t count) nothrow @nogc
{
    T[] slice = mallocSliceNoInit!T(count);
    static if (is(T == struct))
    {
        // we must avoid calling struct destructors with uninitialized memory
        for(size_t i = 0; i < count; ++i)
        {
            T uninitialized;
            memcpy(&slice[i], &uninitialized, T.sizeof); // memcpy OK
        }
    }
    else
        slice[0..count] = T.init;
    return slice;
}

/// Allocates a slice with `malloc`, but does not initialize the content.
T[] mallocSliceNoInit(T)(size_t count) nothrow @nogc
{
    // Changed from Dplug: fail on an overflowing size or a failed malloc,
    // rather than return a slice over a null pointer.
    if (count > size_t.max / T.sizeof)
        onOutOfMemoryError();
    T* p = cast(T*) malloc(count * T.sizeof);
    if (p is null && count != 0)
        onOutOfMemoryError();
    return p[0..count];
}

/// Frees a slice allocated with `mallocSlice`.
void freeSlice(T)(const(T)[] slice) nothrow @nogc
{
    free(cast(void*)(slice.ptr)); // const cast here
}
